apiVersion: apps/v1
kind: Deployment
metadata:
  name: workon-deployment
spec:
  selector:
    matchLabels:
      app: workon
  replicas: 2
  template:
    metadata:
      labels:
        app: workon
    spec:
      containers:
      - name: workon
        image: rfahham/workon:2.0.0
        # command: ["sleep", "infinity"]
        ports:
        - containerPort: 80